# Generated by Django 4.2.10 on 2024-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="код верификации"
            ),
        ),
    ]
