# Generated by Django 4.2.10 on 2024-05-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
