# Generated by Django 4.2.10 on 2024-03-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_blog_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="slug",
            field=models.CharField(
                blank=True, max_length=60, null=True, unique=True, verbose_name="Слог"
            ),
        ),
    ]
