# Generated by Django 4.2.10 on 2024-04-20 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="version",
            name="verification_code",
            field=models.CharField(
                blank=True, max_length=9, null=True, verbose_name="Код верификации"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 20, 12, 56, 37, 521070),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 20, 12, 56, 37, 521078),
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
