# Generated by Django 4.2.10 on 2024-04-21 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_version_verification_code_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 21, 11, 31, 11, 253245),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 21, 11, 31, 11, 253254),
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
