# Generated by Django 4.2.10 on 2024-05-01 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_product_owner_alter_product_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 1, 12, 52, 20, 971360),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 1, 12, 52, 20, 971368),
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
