# Generated by Django 4.2.10 on 2024-05-07 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_product_created_at_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("name",),
                "permissions": [
                    ("set_published_product", "Can publish product"),
                    ("change_description_product", "Can change description product"),
                    ("change_category_product", "Can change category product"),
                ],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 7, 11, 44, 53, 422948),
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 5, 7, 11, 44, 53, 422959),
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
